/**
 * This file was adapted from the "Sample Controller Skeleton"
 * generated by SceneBuilder.
 */

package control;

import boundary.Main;
import entity.Item;
import entity.ItemComponent;
import entity.ItemContainer;
import java.lang.Integer;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.function.UnaryOperator;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.control.TextFormatter;
import javafx.scene.control.TreeItem;
import javafx.scene.control.TreeView;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;

/*
 * Singleton design pattern
 */
public class DashboardController {
  @FXML
  private ResourceBundle resources;

  @FXML
  private URL location;

  @FXML
  private TextArea infoLog = new TextArea();

  @FXML
  private TreeView<ItemComponent> farmTreeView = new TreeView<ItemComponent>();

  @FXML
  private TextField selectionName = new TextField();

  @FXML
  private TextField selectionLocationX = new TextField();

  @FXML
  private TextField selectionLocationY = new TextField();

  @FXML
  private TextField selectionLength = new TextField();

  @FXML
  private TextField selectionWidth = new TextField();

  @FXML
  private TextField selectionHeight = new TextField();

  @FXML
  private TextField selectionPrice = new TextField();

  @FXML
  private TextField selectionAggregatePrice = new TextField();

  @FXML
  private Pane farmMap;

  private UnaryOperator<TextFormatter.Change> intFilter = new UnaryOperator<TextFormatter.Change>() {

    public TextFormatter.Change apply(TextFormatter.Change textField) {
      textField.setText(textField.getText().replaceAll("[^0-9]", ""));
      return textField;
    }
  };

  // Only here for singleton design pattern exercise
  private DashboardController instance = null;

  private Main main;

  /*
   * Only here for singleton design pattern exercise
   * Only public because FXML requires it to be
   */
  public DashboardController() {}

  /*
   * Only here for singleton design pattern exercise
   */
  public DashboardController getInstance() {
    if (instance == null) instance = new DashboardController();
    return instance;
  }

  @FXML
  public void initialize() {
    assert infoLog !=
    null : "fx:id=\"infoLog\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert farmTreeView !=
    null : "fx:id=\"farmTreeView\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionName !=
    null : "fx:id=\"selectionName\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionLocationX !=
    null : "fx:id=\"selectionLocationX\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionLocationY !=
    null : "fx:id=\"selectionLocationY\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionLength !=
    null : "fx:id=\"selectionLength\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionWidth !=
    null : "fx:id=\"selectionWidth\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionHeight !=
    null : "fx:id=\"selectionHeight\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionPrice !=
    null : "fx:id=\"selectionPrice\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert selectionAggregatePrice !=
    null : "fx:id=\"selectionAggregatePrice\" was not injected: check your FXML file 'Dashboard.fxml'.";
    assert farmMap !=
    null : "fx:id=\"farmMap\" was not injected: check your FXML file 'Dashboard.fxml'.";
    infoLog.setEditable(false);
    selectionLocationX.setTextFormatter(new TextFormatter<>(intFilter));
    selectionLocationY.setTextFormatter(new TextFormatter<>(intFilter));
    selectionLength.setTextFormatter(new TextFormatter<>(intFilter));
    selectionWidth.setTextFormatter(new TextFormatter<>(intFilter));
    selectionHeight.setTextFormatter(new TextFormatter<>(intFilter));
    selectionPrice.setTextFormatter(new TextFormatter<>(intFilter));
    selectionAggregatePrice.setEditable(false);
  }

  public void setMain(Main main) {
    this.main = main;
    farmTreeView.setEditable(false);
    farmTreeView.setRoot(
      new TreeItem<ItemComponent>(main.getRootItemContainer())
    );
    farmTreeView.getRoot().setExpanded(true);
  }

  private void addToInfoLog(String message) {
    infoLog.appendText(String.format("%s\n", message));
  }

  private TreeItem<ItemComponent> getCurrentSelection() {
    return farmTreeView.getSelectionModel().getSelectedItem();
  }

  private void addToFarmTreeView(ItemComponent component) {
    TreeItem<ItemComponent> selection = getCurrentSelection();
    if (selection == null) {
      addToInfoLog("Failed to add; nothing is selected");
      return;
    }
    ItemComponent selectionValue = selection.getValue();
    if (selectionValue instanceof Item) addToInfoLog(
      "Failed to add; Item is selected"
    ); else { // selection is an ItemContainer
      selection.getValue().addItemComponent(component);
      TreeItem<ItemComponent> treeItem = new TreeItem<ItemComponent>(component);
      treeItem.setExpanded(true);
      selection.getChildren().add(treeItem);
	  farmMap.getChildren().add(component.getRectangle());
      addToInfoLog(
        String.format("%s added", component.getClass().getSimpleName())
      );
    }
  }

  private void changeRectangle(ItemComponent component) {
	  // remove the rectangle and add a new one for an illusion of updating it
	  farmMap.getChildren().remove(component.getRectangle());
	  component.setRectangle(new Rectangle(component.getLocationX(), component.getLocationY(), component.getLength(), component.getWidth()));
	  farmMap.getChildren().add(component.getRectangle());
  }

  @FXML
  /*
   * Called when the "Add Item" button is clicked
   */
  public void addItem(ActionEvent event) {
    addToFarmTreeView(new Item(new Rectangle()));
  }

  @FXML
  /*
   * Called when the "Add ItemContainer" button is clicked
   */
  public void addItemContainer(ActionEvent event) {
    addToFarmTreeView(new ItemContainer(new Rectangle()));
  }

  @FXML
  /*
   * Called when the "Delete Selection" button is clicked
   */
  public void deleteSelection(ActionEvent event) {
    TreeItem<ItemComponent> selection = getCurrentSelection();
    if (selection == null) addToInfoLog(
      "Failed to delete; nothing is selected"
    ); else if (selection == farmTreeView.getRoot()) addToInfoLog(
      "Failed to delete; Root is selected"
    ); else {
      ItemComponent component = selection.getValue();
      TreeItem<ItemComponent> parent = selection.getParent();
      parent.getValue().deleteItemComponent(selection.getValue());
      parent.getChildren().remove(selection);
      farmMap.getChildren().remove(component.getRectangle());
      addToInfoLog("Selection deleted");
      loadSelectionDetails();
    }
  }

  private void refreshSelectionAggregatePrice(ItemComponent component) {
    selectionAggregatePrice.setText(
      String.format("%d", component.getAggregatePrice())
    );
  }

  @FXML
  /*
   * Called when the "Farm TreeView" is interacted with
   */
  public void loadSelectionDetails() {
    TreeItem<ItemComponent> selection = getCurrentSelection();
    if (selection == null) return;
    ItemComponent component = selection.getValue();
    selectionName.setText(component.getName());
    selectionLocationX.setText(String.format("%d", component.getLocationX()));
    selectionLocationY.setText(String.format("%d", component.getLocationY()));
    selectionLength.setText(String.format("%d", component.getLength()));
    selectionWidth.setText(String.format("%d", component.getWidth()));
    selectionHeight.setText(String.format("%d", component.getHeight()));
    selectionPrice.setText(String.format("%d", component.getPrice()));
    refreshSelectionAggregatePrice(component);
    addToInfoLog("Selection details loaded");
  }

  @FXML
  /*
   * Called when the "Update Selection" button is clicked
   */
  public void updateSelection(ActionEvent event) {
    TreeItem<ItemComponent> selection = getCurrentSelection();
    if (selection == null) addToInfoLog(
      "Failed to update; nothing is selected"
    ); else if (selection == farmTreeView.getRoot()) addToInfoLog(
      "Failed to update; Root is selected"
    ); else {
      ItemComponent component = selection.getValue();
      component.setName(selectionName.getText());
      component.setLocationX(Integer.parseInt(selectionLocationX.getText()));
      component.setLocationY(Integer.parseInt(selectionLocationY.getText()));
      component.setLength(Integer.parseInt(selectionLength.getText()));
      component.setWidth(Integer.parseInt(selectionWidth.getText()));
      component.setHeight(Integer.parseInt(selectionHeight.getText()));
      component.setPrice(Integer.parseInt(selectionPrice.getText()));
      changeRectangle(component);
      selection.setValue(component);
      refreshSelectionAggregatePrice(component);
      farmTreeView.refresh();
      addToInfoLog("Selection updated");
    }
  }

  @FXML
  /*
   * Called when the "Deploy Drone" button is clicked
   */
  public void deployDrone(ActionEvent event) {
    addToInfoLog("Drone deployed");
  }
}
